export const FETCH_SEARCH_TWITTER = 'FETCH_SEARCH_TWITTER';
export const RECEIVE_SEARCH_TWITTER = 'RECEIVE_SEARCH_TWITTER';
export const FETCH_NEXT_TWEETS = 'FETCH_NEXT_TWEETS';
export const RECEIVE_NEXT_TWEETS = 'RECEIVE_NEXT_TWEETS';
export const RESET_TWEETS = 'RESET_TWEETS';